AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-backend
  SAM Template for the Cloud Resume Challenge serverless backend infrastructure.

Resources:
  # 1. Define the DynamoDB Database Table
  CloudResumeCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: cloud-resume-counter
      PrimaryKey:
        Name: id
        Type: String

  # 2. Define the Lambda Function & API Gateway Route
  CloudResumeCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: counter_function/
      Handler: app.lambda_handler
      Runtime: python3.12 # Ensure this matches the version you configured earlier
      Policies:
        # Give this Lambda function full permission to manage the table defined above
        - DynamoDBCrudPolicy:
            TableName: !Ref CloudResumeCounterTable

# 3. Create an AI Chatbot
  CloudResumeAiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ai_function/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      Events:
        ChatApi:
          Type: HttpApi
          Properties:
            Path: /chat
            Method: post
            ApiId: !Ref ServerlessHttpApi

  # 4. Define Global HTTP API Gateway Configuration
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type

Events:
        # Automatically create an API Gateway HTTP API route mapping to the function
        GetCounterApi:
          Type: HttpApi
          Properties:
            Path: /counter
            Method: get
            CorsConfiguration:
              AllowOrigins:
                - '*'  # This allows your CloudFront domain to read the data safely
              AllowMethods:
                - GET
                - OPTIONS
              AllowHeaders:
                - Content-Type

Outputs:
  # This will print your brand new public Invoke URL right into the terminal on deployment
  CloudResumeApiUrl:
    Description: "Public API Gateway Endpoint URL"
    Value: !Sub "https://3lqz0x86qe.execute-api.us-east-2.amazonaws.com/counter"